<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="RACD-002157" name="Test" tests="11" failures="1" timestamp="23 May 2019 09:56:17 GMT" time="17.325" errors="0">
  <testcase name="TrackTransferModule" time="0.008" classname="com.qa.extentreport.TestClass.TestOfExtentReport"/>
  <testcase name="EnterWrongMTCNNumber" time="0.001" classname="com.qa.extentreport.TestClass.TestOfExtentReport"/>
  <testcase name="ErrorMessageInString" time="0.001" classname="com.qa.extentreport.TestClass.TestOfExtentReport"/>
  <testcase name="ErrorMessageInNumber" time="0.001" classname="com.qa.extentreport.TestClass.TestOfExtentReport"/>
  <testcase name="EnterCorrectMTCNnumber" time="0.001" classname="com.qa.extentreport.TestClass.TestOfExtentReport"/>
  <testcase name="StatusOfValidMTCNnumber" time="3.001" classname="com.qa.extentreport.TestClass.TestOfExtentReport"/>
  <testcase name="TrackNewTransfer" time="0.001" classname="com.qa.extentreport.TestClass.TestOfExtentReport"/>
  <testcase name="DontHaveMTCNNumber" time="0.003" classname="com.qa.extentreport.TestClass.TestOfExtentReport"/>
  <testcase name="SearchMTCNWithoutMTCNNumber" time="0.001" classname="com.qa.extentreport.TestClass.TestOfExtentReport">
    <skipped/>
  </testcase> <!-- SearchMTCNWithoutMTCNNumber -->
  <testcase name="FailingThisMethod" time="0.004" classname="com.qa.extentreport.TestClass.TestOfExtentReport">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.qa.extentreport.TestClass.TestOfExtentReport.FailingThisMethod(TestOfExtentReport.java:116)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- FailingThisMethod -->
  <testcase name="SenderPhoneNumberModule" time="0.001" classname="com.qa.extentreport.TestClass.TestOfExtentReport"/>
</testsuite> <!-- Test -->
